import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { Timestamp } from "firebase/firestore";

// Define the shape of a community object
export interface Community {
  id: string;
  creatorId: string;
  numberOfMembers: number;
  privacyType: "public" | "restricted" | "private";
  createdAt?: Timestamp;
  imageUrl?: string;
}

// Define the shape of a community snippet object
interface CommunitySnippet {
  communityId: string;
  isModerator: boolean;
  imageUrl: string;
}

// Define the shape of the community state
interface CommunityState {
  mySnippets: CommunitySnippet[];
}

// Define the initial state of the community state
const initialState: CommunityState = {
  mySnippets: [],
};

// Create a slice for the community state
const communitySlice = createSlice({
  name: "community",
  initialState,
  reducers: {
    // Define a reducer to update the entire community state
    updateCommunityState: (state, action: PayloadAction<CommunityState>) => {
      return action.payload;
    },
  },
});

// Export the reducer function generated by createSlice
export default communitySlice.reducer;
